version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  Front_end_deployment:
    working_directory: ~/app/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-frontend
      - run:
          name: front_end_build
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive --acl public-read ./www s3://udagram-heidar/
  back_end_deployment:
    working_directory: ~/app/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram-api
      - run:
          name: Build and Archive Server
          command: |-
            npm run build
            npm run setEnv
            printenv > www/.env
      - aws-cli/install
      - run:
          name: Deploy Server
          command: |-
            aws s3 cp ./www/Archive.zip s3://elasticbeanstalk-us-east-1-514849120252/
            aws elasticbeanstalk create-application-version --application-name udagramheidar --version-label V2 --source-bundle S3Bucket="elasticbeanstalk-us-east-1-514849120252",S3Key="Archive.zip"
            aws elasticbeanstalk update-environment --application-name udagramheidar --environment-name Udagramheidar-env --version-label V2
workflows:
  build&deploy:
    jobs:
      - Front_end_deployment:
        filters:
          branches:
            only: main
      - back_end_deployment:
        filters:
          branches:
            only: main